# Generated by Django 5.1.4 on 2024-12-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financefuture', '0002_remove_financialhealth_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialhealth',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
